### PR TITLE
`cd` into the directory containing red executable before executing script

### LINKED ISSUE #21: When the redPath contains a space hitting f6 or f7 will not work.
I am using windows7 and I am using version 0.2.2 of the extension

If the redPath contains a space in it then hitting f6 or f7 will not work. The problem is that the command that gets generated in the integrated console does not place quotes around the path to the red executable. It does, however, place quotes around the path to the target file.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #21

### CODE REVIEW

**Comment by ghost** [comment]
Tested on Windows 10.

@qtxie Please review.

**Comment by qtxie** [comment]
Thanks. :+1:

File: src/providers/commandsProvider.ts [hunk 1]
```diff
@@ -94,25 +99,21 @@ function execCommand(currentRedPath: string, command: string, fileUri?: vscode.U
...
             if (redTool) {
-                text = `${currentRedPath} --cli "${filePath}"`;
+                text = `${redExecutable} --cli "${filePath}"`;
             } else {
-                text = `${currentRedPath} "${filePath}"`;
+                text = `${redExecutable} "${filePath}"`;
             }
         } break;
         case Commands.Red_Compile: {
-            buildDir = redSettings.buildDir ||
```
Comment (qtxie) [inline src/providers/commandsProvider.ts]: Why remove buildDir?

Comment (ghost) [reply src/providers/commandsProvider.ts]: Earlier buildDir was being used to `cd` into the directory that contains the source code.
But then the issue was that if red executable is in a directory with spaces, the command executed would be something like this, which is wrongs because the space breaks up the command.
```
C:\red space\red.exe -c "C:\Users\abc\desktop\a.red"
```
I tried to add quotes to the red executable path so that the command would become
```
"C:\red space\red.exe" -c "C:\Users\abc\desktop\a.red"
```
but that is not portable even on windows, for eg. it works on `cmd` but not on `powershell`.

So what I did was to `cd` into the directory containing `red.exe`. And after that pass the full path to the source code as well as the output file name. 
Therefore the earlier terminal command now changes to -
```
cd "C:\red space\"
red.exe -o "C:\Users\abc\desktop\a" -c "C:\Users\abc\desktop\a.red"
```

Since the output IMO should be generated in the same directory as the source code (atleast until a build/package manager arises), therefore AFAICT there is no need for having a `buildDir` right now.

Comment (qtxie) [reply src/providers/commandsProvider.ts]: Yes. `cd` into the directory containing `red.exe` is better. It would be better to keep `red.buildDir`. Just check if it is set or not. If it's set, just output to the buildDir.

Comment (ghost) [reply src/providers/commandsProvider.ts]: Re-added buildDir.

> Just check if it is set or not.
  
I don't think that would be needed since if `buildDir` is not set, it automatically sets it to `filePath`
